# Generated by Django 2.2.7 on 2019-12-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sightings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField(blank=True, help_text='Latitude of sighting')),
                ('Longitude', models.FloatField(blank=True, help_text='Longitude of sighting')),
                ('UniqueSquirrelID', models.CharField(blank=True, help_text='Unique squirrel ID', max_length=100)),
                ('Shift', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Shift of sighting', max_length=2)),
                ('Date', models.DateField(blank=True, help_text='Date of sighting')),
                ('Age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Age of squirrel', max_length=10)),
                ('PrimaryFurColor', models.CharField(blank=True, choices=[('Black', 'Black'), ('Gray', 'Gray'), ('Cinnamon', 'Cinnamon')], help_text='Primary fur color', max_length=10)),
                ('Location', models.CharField(blank=True, choices=[('Above Ground', 'Above Ground'), ('Ground Plane', 'Ground Plane')], help_text='Sighting location', max_length=20)),
                ('SpecificLocation', models.CharField(blank=True, help_text='Specific location of sighting', max_length=100)),
                ('OtherActivities', models.CharField(blank=True, help_text='Other activities', max_length=100)),
                ('Running', models.CharField(blank=True, choices=[('true', 'true'), ('false', 'false')], help_text='Running? T/F', max_length=10)),
                ('Chasing', models.CharField(blank=True, choices=[('true', 'true'), ('false', 'false')], help_text='Chasing? T/F', max_length=10)),
                ('Climbing', models.CharField(blank=True, choices=[('true', 'true'), ('false', 'false')], help_text='Climbing? T/F', max_length=10)),
                ('Eating', models.CharField(blank=True, choices=[('true', 'true'), ('false', 'false')], help_text='Eating? T/F', max_length=10)),
                ('Foraging', models.CharField(blank=True, choices=[('true', 'true'), ('false', 'false')], help_text='Foraging? T/F', max_length=10)),
                ('Kuks', models.CharField(blank=True, choices=[('true', 'true'), ('false', 'false')], help_text='Kuks? T/F', max_length=10)),
                ('Quaas', models.CharField(blank=True, choices=[('true', 'true'), ('false', 'false')], help_text='Quaas? T/F', max_length=10)),
                ('Moans', models.CharField(blank=True, choices=[('true', 'true'), ('false', 'false')], help_text='Moans? T/F', max_length=10)),
                ('TailFlags', models.CharField(blank=True, choices=[('true', 'true'), ('false', 'false')], help_text='Tail Flags? T/F', max_length=10)),
                ('TailTwitches', models.CharField(blank=True, choices=[('true', 'true'), ('false', 'false')], help_text='Tail Twitches? T/F', max_length=10)),
                ('Approaches', models.CharField(blank=True, choices=[('true', 'true'), ('false', 'false')], help_text='Approaches? T/F', max_length=10)),
                ('Indifferent', models.CharField(blank=True, choices=[('true', 'true'), ('false', 'false')], help_text='Indifferent? T/F', max_length=10)),
                ('RunsFrom', models.CharField(blank=True, choices=[('true', 'true'), ('false', 'false')], help_text='Runs From? T/F', max_length=10)),
            ],
        ),
    ]
